# Generated by Django 3.2 on 2021-05-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20210508_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
