# Generated by Django 3.2 on 2021-05-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_land_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
