# Generated by Django 3.2 on 2021-05-13 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_land_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProperty',
            fields=[
                ('land_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Core.land')),
            ],
            bases=('Core.land',),
        ),
    ]
