# Generated by Django 3.2 on 2021-05-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_otherproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherProperty',
        ),
        migrations.CreateModel(
            name='OtherProperty',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Core.land',),
        ),
    ]
