# Generated by Django 3.2 on 2021-05-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_ranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherproperty',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ranch',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
